Add lerna specific steps for bootstrapping packages

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-if [ -f $1/package.json ]; then
-  echo 'Node.js'
+if [ -f $1/lerna.json ]; then
+  echo 'Lerna'
   exit 0
 fi
 
->&2 echo 'Node.js: package.json not found in application root'
+>&2 echo 'Lerna: lerna.json not found in application root'
 exit 1
